name: Publish Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build Docker image
        run: docker build -t cicd-project4:${{ github.sha }} ./app

      - name: Run Docker container
        run: |
          docker run -d \
            --name cicd-project4-test \
            -p 8080:80 \
            cicd-project4:${{ github.sha }}

      - name: Wait for application
        run: sleep 5

      - name: Test application
        run: |
          curl --fail http://localhost:8080
          curl --fail http://localhost:8080 |
            grep "Cloud DevOps CI/CD Pipeline"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.1.1
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag \
            cicd-project4:${IMAGE_TAG} \
            ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}

          docker push \
            ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}

      - name: Clean up test container
        if: always()
        run: |
          docker stop cicd-project4-test || true
          docker rm cicd-project4-test || true
